### ISSUE TITLE
Make CL_KG helper ontology (separate ODK)

### ISSUE THREAD

**Issue by dosumis** [Cellular-Semantics/CL_KG#31]
Helper ontology content:

- [x] 1. EFO assay terms extracted using ROBOT extract Mireot https://robot.obolibrary.org/extract#mireot + lower bound = assay terms from [CxG schema](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.2.0/schema.md#assay_ontology_term_id). Upper bound ["EFO:0002772"](https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0002772) + ["EFO:0010183"](https://www.ebi.ac.uk/ols4/ontologies/efo/classes?obo_id=EFO%3A0010183) for single cell library construction

2. ...

**Comment by ubyndr** [comment]
The task related to item number 1 has been completed. Please refer to the following pull request for details: [Cellular-Semantics/cl_kg_helper#1](https://github.com/Cellular-Semantics/cl_kg_helper/pull/1).

**Comment by ubyndr** [comment]
We should close this issue and create a new one for any follow-up requirements, if needed.
