### ISSUE TITLE
Define Cypher queries for finding new terms.

### ISSUE THREAD

**Issue by ubyndr** [Cellular-Semantics/CL_KG#4]
Copied from https://github.com/cellannotation/CAS-LinkML/issues/5 which is created by @dosumis 

Query 1: Find leaf node CL terms with nested cell sets underneath

Cypher query for leaf nodes: 

```cypher
MATCH p=(c:Class:Cell)<-[:composed_primarily_of]-(s1)<-[:subcluster_of*..]-(s2) where not (c)<-[:SUBCLASSOF]-() return p
```

Example results from Sikemma:

<img width="878" alt="image" src="https://github.com/cellannotation/CAS-LinkML/assets/112839/4a90d9dd-40ac-4bb7-9af7-c238b6abb7ba">

Misses some potentially interesting cases where CL term is not leaf node.  

<img width="630" alt="image" src="https://github.com/cellannotation/CAS-LinkML/assets/112839/bda36769-140d-4661-a18f-d76fae3df3d7">

However, without the leaf node clause, most datasets will return too much to review.

Query to find General term used for specific class.  

e.g. T-Cell here:

<img width="483" alt="image" src="https://github.com/cellannotation/CAS-LinkML/assets/112839/9587df72-668a-4b3f-a4b4-7a06bfe34e50">

Candidate query:

```cypher
MATCH p=(c:Class:Cell)<-[:composed_primarily_of]-(s1:Cluster) where (c)<-[:SUBCLASSOF]-() and not (s1)<-[:subcluster_of]-() return p
```
Looks promising - and at least in this case it returns a set of relatively easy to assess results

<img width="349" alt="image" src="https://github.com/cellannotation/CAS-LinkML/assets/112839/67226c10-9915-405f-bd85-5969baca9f08">

c.label | s1.label | More specific term needed* | CL term to use | Notes
-- | -- | -- | -- |  -- 
serous secreting cell | SMG serous (nasal) | Y |  | SMG = submucosal gland.  We have no nasal SMG serous term.
tracheobronchial goblet cell | Goblet (subsegmental) | ? |  |  Need to check if could be more precise | 
tracheobronchial serous cell | SMG serous (bronchial) | n  | serous secreting cell of bronchus submucosal gland
bronchial goblet cell | Goblet (bronchial) | n | | 
CD4-positive, alpha-beta T cell | CD4 T cells | n | | 
mucus secreting cell | SMG mucous | n | mucus secreting cell of bronchus submucosal gland | |
ciliated columnar cell of tracheobronchial tree | Multiciliated (non-nasal) | n
dendritic cell | Migratory DCs | y || 
lung macrophage | Interstitial Mph perivascular | y || "perivascular macrophage" is currently brain specific!  We also have lung interstitial macrophage
plasmacytoid dendritic cell | Plasmacytoid DCs | n || 
smooth muscle cell | SM activated stress response | y? || 
epithelial cell of alveolus of lung | AT0 | Y || 
fibroblast | Subpleural fibroblasts | Y || 
tracheobronchial smooth muscle cell | Smooth muscle | N || 
epithelial cell of lower respiratory   tract | pre-TB secretory | Y | | TB = tracheobronchial
CD8-positive, alpha-beta T cell | CD8 T cells | N || 
T cell | T cells proliferating | N || 
conventional dendritic cell | DC1 | N || 
brush cell of trachebronchial tree | Tuft | N || 

*quick assessment - may not be 100% acurate

**Comment by dosumis** [comment]
https://cellular-semantics.github.io/CL_KG/query_guide/
