### ISSUE TITLE
Specify CURIEs for uniprot 

### ISSUE THREAD

**Issue by dosumis** [Cellular-Semantics/CL_KG#50]
UniProtKB:  https://identifiers.org/uniprot:

Note bioregistry suggests uniprot: - but Translator uses UniProtKB (reflected in bioregistry)
https://bioregistry.io/registry/uniprot

I believe that the Translator use corresponds to Monarch's, which I would like to align with.

**Comment by ubyndr** [comment]
- [ ] Add `UniProtKB: https://identifiers.org/uniprot` to `neo4j2owl-config.yaml`
- [ ] Rename `ns7` in nodes_Protein.csv files from dumps/csv_imports folder to `UniProtKB `
- [ ] Re-run updateprod
