### ISSUE TITLE
Problem with linking markers to Cell_clusters

### ISSUE THREAD

**Issue by dosumis** [Cellular-Semantics/CL_KG#54]
Markers are linked to anonymous clusters.  Some problem with IRIs?

<img width="628" alt="image" src="https://github.com/user-attachments/assets/326a9d72-d187-4c12-b900-3fa6f980089d">

I think the anonymous node with the NSForest markers should be the pericytes node

**Comment by ubyndr** [comment]
Hi @dosumis , Could you please provide more details so I can check the .owl files? Would it also be possible to share the Cypher query you’re using here?

**Comment by ubyndr** [comment]
This should hopefully be resolved with the next pipeline run. We are also trying to make a new CellMark release
